{"title_html": "<h1>Python - Exceptions Handling</h1>", "content": "\n Python - Exceptions Handling \n  \n Advertisements \n \n<!--\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = 468;\ngoogle_ad_height = 60;\ngoogle_ad_format = \"468x60_as\";\ngoogle_ad_type = \"image\";\ngoogle_ad_channel = \"\";\n//-->\n\n\n \n  \n \n Previous Page\n \n \nNext Page \u00a0\n \n  \n  \n Python provides two very important features to handle any unexpected error in your Python programs and to add debugging capabilities in them \u2212 \n \nException Handling \u2212 This would be covered in this tutorial. Here is a list standard Exceptions available in Python: Standard Exceptions.\nAssertions \u2212 This would be covered in Assertions in Python tutorial.\n \n List of Standard Exceptions \u2212 \n \n\nSr.No.\nException Name & Description\n\n\n1\nException\nBase class for all exceptions\n\n\n2\nStopIteration\nRaised when the next() method of an iterator does not point to any object.\n\n\n3\nSystemExit\nRaised by the sys.exit() function.\n\n\n4\nStandardError\nBase class for all built-in exceptions except StopIteration and SystemExit.\n\n\n5\nArithmeticError\nBase class for all errors that occur for numeric calculation.\n\n\n6\nOverflowError\nRaised when a calculation exceeds maximum limit for a numeric type.\n\n\n7\nFloatingPointError\nRaised when a floating point calculation fails.\n\n\n8\nZeroDivisionError\nRaised when division or modulo by zero takes place for all numeric types.\n\n\n9\nAssertionError\nRaised in case of failure of the Assert statement.\n\n\n10\nAttributeError\nRaised in case of failure of attribute reference or assignment.\n\n\n11\nEOFError\nRaised when there is no input from either the raw_input() or input() function and the end of file is reached.\n\n\n12\nImportError\nRaised when an import statement fails.\n\n\n13\nKeyboardInterrupt\nRaised when the user interrupts program execution, usually by pressing Ctrl+c.\n\n\n14\nLookupError\nBase class for all lookup errors.\n\n\n15\nIndexError\nRaised when an index is not found in a sequence.\n\n\n16\nKeyError\nRaised when the specified key is not found in the dictionary.\n\n\n17\nNameError\nRaised when an identifier is not found in the local or global namespace.\n\n\n18\nUnboundLocalError\nRaised when trying to access a local variable in a function or method but no value has been assigned to it.\n\n\n19\nEnvironmentError\nBase class for all exceptions that occur outside the Python environment.\n\n\n20\nIOError\nRaised when an input/ output operation fails, such as the print statement or the open() function when trying to open a file that does not exist.\n\n\n21\nIOError\nRaised for operating system-related errors.\n\n\n22\nSyntaxError\nRaised when there is an error in Python syntax.\n\n\n23\nIndentationError\nRaised when indentation is not specified properly.\n\n\n24\nSystemError\nRaised when the interpreter finds an internal problem, but when this error is encountered the Python interpreter does not exit.\n\n\n25\nSystemExit\nRaised when Python interpreter is quit by using the sys.exit() function. If not handled in the code, causes the interpreter to exit.\n\n\n26\nTypeError\nRaised when an operation or function is attempted that is invalid for the specified data type.\n\n\n27\nValueError\nRaised when the built-in function for a data type has the valid type of arguments, but the arguments have invalid values specified.\n\n\n28\nRuntimeError\nRaised when a generated error does not fall into any category.\n\n\n29\nNotImplementedError\nRaised when an abstract method that needs to be implemented in an inherited class is not actually implemented.\n\n \n Assertions in Python \n An assertion is a sanity-check that you can turn on or turn off when you are done with your testing of the program. \n The easiest way to think of an assertion is to liken it to a raise-if statement (or to be more accurate, a raise-if-not statement). An expression is tested, and if the result comes up false, an exception is raised. \n Assertions are carried out by the assert statement, the newest keyword to Python, introduced in version 1.5. \n Programmers often place assertions at the start of a function to check for valid input, and after a function call to check for valid output. \n The assert Statement \n When it encounters an assert statement, Python evaluates the accompanying expression, which is hopefully true. If the expression is false, Python raises an AssertionError exception. \n The syntax for assert is \u2212 \n \nassert Expression[, Arguments]\n \n If the assertion fails, Python uses ArgumentExpression as the argument for the AssertionError. AssertionError exceptions can be caught and handled like any other exception using the try-except statement, but if not handled, they will terminate the program and produce a traceback. \n Example \n Here is a function that converts a temperature from degrees Kelvin to degrees Fahrenheit. Since zero degrees Kelvin is as cold as it gets, the function bails out if it sees a negative temperature \u2212 \n  Live Demo \n \n#!/usr/bin/python\ndef KelvinToFahrenheit(Temperature):\n   assert (Temperature >= 0),\"Colder than absolute zero!\"\n   return ((Temperature-273)*1.8)+32\nprint KelvinToFahrenheit(273)\nprint int(KelvinToFahrenheit(505.78))\nprint KelvinToFahrenheit(-5)\n \n When the above code is executed, it produces the following result \u2212 \n \n32.0\n451\nTraceback (most recent call last):\nFile \"test.py\", line 9, in <module>\nprint KelvinToFahrenheit(-5)\nFile \"test.py\", line 4, in KelvinToFahrenheit\nassert (Temperature >= 0),\"Colder than absolute zero!\"\nAssertionError: Colder than absolute zero!\n \n What is Exception? \n An exception is an event, which occurs during the execution of a program that disrupts the normal flow of the program's instructions. In general, when a Python script encounters a situation that it cannot cope with, it raises an exception. An exception is a Python object that represents an error. \n When a Python script raises an exception, it must either handle the exception immediately otherwise it terminates and quits. \n Handling an exception \n If you have some suspicious code that may raise an exception, you can defend your program by placing the suspicious code in a try: block. After the try: block, include an except: statement, followed by a block of code which handles the problem as elegantly as possible. \n Syntax \n Here is simple syntax of try....except...else blocks \u2212 \n \ntry:\n   You do your operations here;\n   ......................\nexcept ExceptionI:\n   If there is ExceptionI, then execute this block.\nexcept ExceptionII:\n   If there is ExceptionII, then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n \n Here are few important points about the above-mentioned syntax \u2212 \n \nA single try statement can have multiple except statements. This is useful when the try block contains statements that may throw different types of exceptions.\nYou can also provide a generic except clause, which handles any exception.\nAfter the except clause(s), you can include an else-clause. The code in the else-block executes if the code in the try: block does not raise an exception.\nThe else-block is a good place for code that does not need the try: block's protection.\n \n Example \n This example opens a file, writes content in the, file and comes out gracefully because there is no problem at all \u2212 \n  Live Demo \n \n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   fh.write(\"This is my test file for exception handling!!\")\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\nelse:\n   print \"Written content in the file successfully\"\n   fh.close()\n \n This produces the following result \u2212 \n \nWritten content in the file successfully\n \n Example \n This example tries to open a file where you do not have write permission, so it raises an exception \u2212 \n  Live Demo \n \n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"r\")\n   fh.write(\"This is my test file for exception handling!!\")\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\nelse:\n   print \"Written content in the file successfully\"\n \n This produces the following result \u2212 \n \nError: can't find file or read data\n \n The except Clause with No Exceptions \n You can also use the except statement with no exceptions defined as follows \u2212 \n \ntry:\n   You do your operations here;\n   ......................\nexcept:\n   If there is any exception, then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n \n This kind of a try-except statement catches all the exceptions that occur. Using this kind of try-except statement is not considered a good programming practice though, because it catches all exceptions but does not make the programmer identify the root cause of the problem that may occur. \n The except Clause with Multiple Exceptions \n You can also use the same except statement to handle multiple exceptions as follows \u2212 \n \ntry:\n   You do your operations here;\n   ......................\nexcept(Exception1[, Exception2[,...ExceptionN]]]):\n   If there is any exception from the given exception list, \n   then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n \n The try-finally Clause \n You can use a finally: block along with a try: block. The finally block is a place to put any code that must execute, whether the try-block\nraised an exception or not. The syntax of the try-finally statement is this \u2212 \n \ntry:\n   You do your operations here;\n   ......................\n   Due to any exception, this may be skipped.\nfinally:\n   This would always be executed.\n   ......................\n \n You cannot use else clause as well along with a finally clause. \n Example \n  Live Demo \n \n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   fh.write(\"This is my test file for exception handling!!\")\nfinally:\n   print \"Error: can\\'t find file or read data\"\n \n If you do not have permission to open the file in writing mode, then this will produce the following result \u2212 \n \nError: can't find file or read data\n \n Same example can be written more cleanly as follows \u2212 \n  Live Demo \n \n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   try:\n      fh.write(\"This is my test file for exception handling!!\")\n   finally:\n      print \"Going to close the file\"\n      fh.close()\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\n \n When an exception is thrown in the try block, the execution immediately passes to the finally block. After all the statements in the finally block are executed, the exception is raised again and is handled in the except statements if present in the next higher layer of the try-except statement. \n Argument of an Exception \n An exception can have an argument, which is a value that gives additional information about the problem. The contents  of the argument vary by exception. You capture an exception's argument by supplying a variable in the except clause as follows \u2212 \n \ntry:\n   You do your operations here;\n   ......................\nexcept ExceptionType, Argument:\n   You can print value of Argument here...\n \n If you write the code to handle a single exception, you can have a variable follow the name of the exception in the except statement. If you are trapping multiple exceptions, you can have a variable follow the tuple of the exception. \n This variable receives the value of the exception mostly containing the cause of the exception. The variable can receive a single value or multiple values in the form of a tuple. This tuple usually contains the error string, the error number, and an error location. \n Example \n Following is an example for a single exception \u2212 \n  Live Demo \n \n#!/usr/bin/python\n\n# Define a function here.\ndef temp_convert(var):\n   try:\n      return int(var)\n   except ValueError, Argument:\n      print \"The argument does not contain numbers\\n\", Argument\n\n# Call above function here.\ntemp_convert(\"xyz\");\n \n This produces the following result \u2212 \n \nThe argument does not contain numbers\ninvalid literal for int() with base 10: 'xyz'\n \n Raising an Exceptions \n You can raise exceptions in several ways by using the raise statement. The general syntax for the raise statement is as follows. \n Syntax \n \nraise [Exception [, args [, traceback]]]\n \n Here, Exception is the type of exception (for example, NameError) and argument is a value for the exception argument. The argument is optional; if not supplied, the exception argument is None. \n The final argument, traceback, is also optional (and rarely used in practice), and if present, is the traceback object used for the exception. \n Example \n An exception can be a string, a class or an object. Most of the exceptions that the Python core raises are classes, with an argument that is an instance of the class. Defining new exceptions is quite easy and can be done as follows \u2212 \n \ndef functionName( level ):\n   if level < 1:\n      raise \"Invalid level!\", level\n      # The code below to this would not be executed\n      # if we raise the exception\n \n Note: In order to catch an exception, an \"except\" clause must refer to the same exception thrown either class object or simple string. For example, to capture above exception, we must write the except clause as follows \u2212 \n \ntry:\n   Business Logic here...\nexcept \"Invalid level!\":\n   Exception handling here...\nelse:\n   Rest of the code here...\n \n User-Defined Exceptions \n Python also allows you to create your own exceptions by deriving classes from the standard built-in exceptions. \n Here is an example related to RuntimeError. Here, a class is created that is subclassed from RuntimeError. This is useful when you need to display more specific information when an exception is caught. \n In the try block, the user-defined exception is raised and caught in the except block. The variable e is used to create an instance of the class Networkerror. \n \nclass Networkerror(RuntimeError):\n   def __init__(self, arg):\n      self.args = arg\n \n So once you defined above class, you can raise the exception as follows \u2212 \n \ntry:\n   raise Networkerror(\"Bad hostname\")\nexcept Networkerror,e:\n   print e.args\n \n  \n \n Previous Page\n \n \n Print\n \n \nNext Page \u00a0\n \n  \n  PRINTING ENDS HERE  \n \nAdvertisements\n<!--\nvar width = 580;\nvar height = 400;\nvar format = \"580x400_as\";\nif( window.innerWidth < 468 ){\n   width = 300;\n   height = 250;\n   format = \"300x250_as\";\n}\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = width;\ngoogle_ad_height = height;\ngoogle_ad_format = format;\ngoogle_ad_type = \"image\";\ngoogle_ad_channel =\"\";\n//-->\n\n\n \n", "url": "https://www.tutorialspoint.com/python/python_exceptions.htm", "html": "<!DOCTYPE html>\n\n<!--[if IE 8]><html class=\"ie ie8\"> <![endif]-->\n<!--[if IE 9]><html class=\"ie ie9\"> <![endif]-->\n<!--[if gt IE 9]><!--> <html> <!--<![endif]-->\n<head>\n<!-- Basic -->\n<meta charset=\"utf-8\"/>\n<title>Python Exceptions Handling</title>\n<meta content=\"Python Exceptions Handling - Learn Python in simple and easy steps starting from basic to advanced concepts with examples including Python Syntax Object Oriented Language, Methods, Tuples, Tools/Utilities, Exceptions Handling, Sockets, GUI, Extentions, XML Programming.\" name=\"description\">\n<meta content=\"Python, Tutorials, Learning, Beginners, Basics, Object Oriented Language, Methods, Overriding, Networking, Multithreading,Methods, Tuples, Tools/Utilities, Exceptions Handling, Sockets, GUI, Extentions, XML, Programming.\" name=\"Keywords\"/>\n<base href=\"https://www.tutorialspoint.com/\"/>\n<link href=\"/favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\"/>\n<meta content=\"width=device-width,initial-scale=1.0,user-scalable=yes\" name=\"viewport\"/>\n<meta content=\"en_US\" property=\"og:locale\">\n<meta content=\"website\" property=\"og:type\"/>\n<meta content=\"471319149685276\" property=\"fb:app_id\"/>\n<meta content=\"www.tutorialspoint.com\" property=\"og:site_name\"/>\n<meta content=\"yes\" name=\"apple-mobile-web-app-capable\"/>\n<meta content=\"black\" name=\"apple-mobile-web-app-status-bar-style\"/>\n<meta content=\"tutorialspoint.com\" name=\"author\"/>\n<script src=\"https://www.tutorialspoint.com/theme/js/script-min-v4.js?v=2\" type=\"text/javascript\"></script>\n<link href=\"https://www.tutorialspoint.com/theme/css/style-min.css?v=3.1\" rel=\"stylesheet\"/>\n<script>\r\nfunction openNav() {\t\r\n  document.getElementById(\"mySidenav\").style.width = \"250px\";\r\n  document.getElementById(\"right_obs\").style.display = \"block\";\r\n}\r\nfunction closeNav() {\r\n  document.getElementById(\"mySidenav\").style.width = \"0\";\r\n  document.getElementById(\"right_obs\").style.display = \"none\";\r\n}\r\nfunction close_obs_sidenav(){\r\n  document.getElementById(\"mySidenav\").style.width = \"0\";\r\n  document.getElementById(\"right_obs\").style.display = \"none\";\r\n}\r\n</script>\n<!-- Head Libs -->\n<!--[if IE 8]>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/theme/css/ie8.css\">\r\n<![endif]-->\n<style>\r\n#privacy-banner {\r\n    position: fixed;\r\n    bottom: 0;\r\n    left: 0;\r\n    width: 100%;\r\n    max-width: 100%;\r\n    padding: 1rem .5rem;\r\n    background: #fff;\r\n    z-index: 1030;\r\n    color: #000;\r\n    font-size: 14px;\r\n    margin: 0;\r\n    display: none;\r\n    border-top: 2px solid rgb(130, 130, 130);\r\n  }\r\n  #privacy-banner p {\r\n    margin: 0;\r\n    color: #000;\r\n    text-align: center;\r\n  }\r\n  #privacy-banner a {\r\n    text-decoration: none;\r\n    margin: 20px auto 0 auto;\r\n    display: block;\r\n    max-width: 150px;\r\n  }\r\n  #privacy-banner a:hover {\r\n    text-decoration: underline;\r\n  }\r\n  #banner-learn {\r\n    color: #000;\r\n  }\r\n  #banner-accept {\r\n    padding: 7px 15px;\r\n    color: #fff;\r\n    border-radius: 5px;\r\n    background:#737373 !important;\r\n  }\r\n  @media (min-width: 768px) {\r\n    #privacy-banner {\r\n      padding: 1.5rem .5rem;\r\n    }\r\n    #privacy-banner a {\r\n      display: inline-block;\r\n      margin: 0 10px;\r\n    }\r\n}\r\npre.prettyprint.tryit {min-height:37px; background: #eee url(/python/images/try-it.jpg) top right no-repeat !important}select{ border:0 !important; outline: 1px inset black !important; outline-offset: -1px !important; }\r\n.btnsbmt{ background: #fdbf00 !important;}\r\nul.nav-list.primary>li a.videolink{    background: none; margin: 0px; padding: 0px; border: 1px solid #d6d6d6;}\r\ndiv.feature-box div.feature-box-icon, .col-md-3 .course-box, li.heading, div.footer-copyright { background: #fdbf00 url(/images/pattern.png) repeat center center !important;}\r\n.sub-main-menu .sub-menuu div:hover, .sub-main-menu .viewall, header nav ul.nav-main li a:hover, button.btn-responsive-nav, header div.search button.btn-default { background: #fdbf00 !important;}\r\n.submenu-item{ border-bottom: 2px solid #fdbf00 !important; border-top: 2px solid #fdbf00 !important }\r\n.ace_scroller{overflow: auto!important;}\r\na.demo{font-family: \"Open Sans\",Arial,sans-serif; background:#fdbf00; color:#fff; font-size:13px; padding:3px 10px; border:1px solid #d6d6d6; position:absolute; right:5px; margin:-6px 17px 0px 0px;}\r\na.demo:hover{opacity:.8}\r\n</style>\n<script>\r\n$(document).ready(function() {\r\n  $('input[name=\"q\"]').keydown(function(event){\r\n    if(event.keyCode == 13) {\r\n      event.preventDefault();\r\n      return false;\r\n    }\r\n  });\r\n});\r\n</script>\n</meta></meta></head>\n<body onload=\"prettyPrint()\">\n<div class=\"wrapLoader\">\n<div class=\"imgLoader\">\n<img alt=\"\" height=\"70\" src=\"/images/loading-cg.gif\" width=\"70\"/>\n</div>\n</div>\n<div class=\"display-none\" id=\"right_obs\" onclick=\"close_obs_sidenav()\"></div>\n<header>\n<div class=\"container\">\n<h1 class=\"logo\">\n<a href=\"index.htm\" title=\"tutorialspoint\">\n<img alt=\"tutorialspoint\" src=\"/python/images/logo.png\"/>\n</a>\n</h1>\n<ul class=\"tp-inline-block pull-right\" id=\"tp-head-icons\">\n<li>\n<div class=\"tp-second-nav tp-display-none tp-pointer\" onclick=\"openNav()\">\n<i class=\"fa fa-th-large fa-lg\"></i>\n</div>\n</li>\n</ul>\n<button class=\"btn btn-responsive-nav btn-inverse\" data-target=\".nav-main-collapse\" data-toggle=\"collapse\" id=\"pull\" style=\"top: 24px!important\"> <i class=\"icon icon-bars\"></i> </button>\n<nav>\n<ul class=\"nav nav-pills nav-top\">\n<li><a href=\"/about/about_careers.htm\" style=\"background: #fffb09; font-weight: bold;\"><i class=\"icon icon-suitcase\"></i> Jobs</a></li>\n<li> <a href=\"/programming_examples/\" target=\"_blank\"><i class=\"fa fa-cubes\"></i> \u00a0Examples</a> </li>\n<li> <a href=\"https://www.tutorialspoint.com/whiteboard.htm\"><img alt=\"Whiteboard\" src=\"theme/css/icons/image-editor.png\" title=\"Whiteboard\"/> \u00a0Whiteboard</a> </li>\n<li> <a href=\"https://www.tutorialspoint.com/netmeeting.php\"><i class=\"fa-camera\"></i> \u00a0Net Meeting</a> </li>\n<li> <a href=\"/online_dev_tools.htm\"> <i class=\"dev-tools-menu\" style=\"opacity:.5\"></i> Tools </a> </li>\n<li> <a href=\"/articles/index.php\"><i class=\"icon icon-file-text-o\"></i> \u00a0Articles</a> </li>\n<li class=\"top-icons\">\n<ul class=\"social-icons\">\n<li class=\"facebook\"><a data-placement=\"bottom\" href=\"https://www.facebook.com/tutorialspointindia\" rel=\"nofollow\" target=\"_blank\" title=\"tutorialspoint @ Facebook\">Facebook</a></li>\n<li class=\"googleplus\"><a data-placement=\"bottom\" href=\"https://plus.google.com/u/0/116678774017490391259/posts\" rel=\"nofollow\" target=\"_blank\" title=\"tutorialspoint @ Google+\">Google+</a></li>\n<li class=\"twitter\"><a data-placement=\"bottom\" href=\"https://www.twitter.com/tutorialspoint\" rel=\"nofollow\" target=\"_blank\" title=\"tutorialspoint @ Twitter\">Twitter</a></li>\n<li class=\"linkedin\"><a data-placement=\"bottom\" href=\"https://www.linkedin.com/company/tutorialspoint\" rel=\"nofollow\" target=\"_blank\" title=\"tutorialspoint @ Linkedin\">Linkedin</a></li>\n<li class=\"youtube\"><a data-placement=\"bottom\" href=\"https://www.youtube.com/channel/UCVLbzhxVTiTLiVKeGV7WEBg\" rel=\"nofollow\" target=\"_blank\" title=\"tutorialspoint YouTube\">YouTube</a></li>\n</ul>\n</li>\n</ul>\n</nav>\n</div>\n<div class=\"sidenav\" id=\"mySidenav\">\n<div class=\"navbar nav-main\">\n<div class=\"container\">\n<nav class=\"nav-main mega-menu\">\n<ul class=\"nav nav-pills nav-main\" id=\"mainMenu\">\n<li class=\"dropdown no-sub-menu\"> <a class=\"dropdown\" href=\"index.htm\"><i class=\"icon icon-home\"></i> Home</a> </li>\n<li class=\"dropdown no-sub-menu\"><a class=\"dropdown\" href=\"/questions/index.php\"><i class=\"fa fa-send\"></i> Q/A </a> </li>\n<li class=\"dropdown\"><a class=\"dropdown\" href=\"tutorialslibrary.htm\"><span class=\"tut-lib\"> Library </span></a></li>\n<li class=\"dropdown no-sub-menu\"><a class=\"dropdown\" href=\"videotutorials/index.htm\"><i class=\"fa-toggle-right\"></i> Videos </a></li>\n<li class=\"dropdown no-sub-menu\"><a class=\"dropdown\" href=\"tutor_connect/index.php\"><i class=\"fa-user\"> </i> Tutors</a></li>\n<li class=\"dropdown no-sub-menu\"><a class=\"dropdown\" href=\"codingground.htm\"><i class=\"fa-code\"></i> Coding Ground </a> </li>\n<li class=\"dropdown no-sub-menu\"><a class=\"dropdown\" href=\"https://store.tutorialspoint.com/\"><i class=\"fa-usd\"></i> Store </a> </li>\n<li class=\"dropdown no-sub-menu\">\n<div class=\"searchform-popup\">\n<input autocomplete=\"off\" class=\"header-search-box\" id=\"search-string\" name=\"q\" onblur=\"if (this.value == '') {this.value = 'Search your favorite tutorials...';}\" onfocus=\"if (this.value == 'Search your favorite tutorials...') {this.value = '';}\" placeholder=\"Search your favorite tutorials...\" type=\"text\"/>\n<div class=\"magnifying-glass\"><i class=\"icon-search\"></i> Search </div>\n</div>\n</li>\n</ul>\n</nav>\n</div>\n</div>\n</div>\n</header></body></html>\n\n<div style=\"clear:both;\"></div>\n<div class=\"main\" role=\"main\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-md-2\">\n<aside class=\"sidebar\">\n<style>\r\n.ts {\r\n   text-align:center !important;\r\n   vertical-align:middle !important;\r\n}\r\n</style>\n<div class=\"mini-logo\">\n<img alt=\"Python Tutorial\" src=\"/python/images/python-mini.jpg\">\n</img></div>\n<ul class=\"nav nav-list primary left-menu\">\n<li class=\"heading\">Python Basic Tutorial</li>\n<li><a href=\"/python/index.htm\" target=\"_top\">Python - Home</a></li>\n<li><a href=\"/python/python_overview.htm\" target=\"_top\">Python - Overview</a></li>\n<li><a href=\"/python/python_environment.htm\" target=\"_top\">Python - Environment Setup</a></li>\n<li><a href=\"/python/python_basic_syntax.htm\" target=\"_top\">Python - Basic Syntax</a></li>\n<li><a href=\"/python/python_variable_types.htm\" target=\"_top\">Python - Variable Types</a></li>\n<li><a href=\"/python/python_basic_operators.htm\" target=\"_top\">Python - Basic Operators</a></li>\n<li><a href=\"/python/python_decision_making.htm\" target=\"_top\">Python - Decision Making</a></li>\n<li><a href=\"/python/python_loops.htm\" target=\"_top\">Python - Loops</a></li>\n<li><a href=\"/python/python_numbers.htm\" target=\"_top\">Python - Numbers</a></li>\n<li><a href=\"/python/python_strings.htm\" target=\"_top\">Python - Strings</a></li>\n<li><a href=\"/python/python_lists.htm\" target=\"_top\">Python - Lists</a></li>\n<li><a href=\"/python/python_tuples.htm\" target=\"_top\">Python - Tuples</a></li>\n<li><a href=\"/python/python_dictionary.htm\" target=\"_top\">Python - Dictionary</a></li>\n<li><a href=\"/python/python_date_time.htm\" target=\"_top\">Python - Date &amp; Time</a></li>\n<li><a href=\"/python/python_functions.htm\" target=\"_top\">Python - Functions</a></li>\n<li><a href=\"/python/python_modules.htm\" target=\"_top\">Python - Modules</a></li>\n<li><a href=\"/python/python_files_io.htm\" target=\"_top\">Python - Files I/O</a></li>\n<li><a href=\"/python/python_exceptions.htm\" target=\"_top\">Python - Exceptions</a></li>\n</ul>\n<ul class=\"nav nav-list primary left-menu\">\n<li class=\"heading\">Python Advanced Tutorial</li>\n<li><a href=\"/python/python_classes_objects.htm\" target=\"_top\">Python - Classes/Objects</a></li>\n<li><a href=\"/python/python_reg_expressions.htm\" target=\"_top\">Python - Reg Expressions</a></li>\n<li><a href=\"/python/python_cgi_programming.htm\" target=\"_top\">Python - CGI Programming</a></li>\n<li><a href=\"/python/python_database_access.htm\" target=\"_top\">Python - Database Access</a></li>\n<li><a href=\"/python/python_networking.htm\" target=\"_top\">Python - Networking</a></li>\n<li><a href=\"/python/python_sending_email.htm\" target=\"_top\">Python - Sending Email</a></li>\n<li><a href=\"/python/python_multithreading.htm\" target=\"_top\">Python - Multithreading</a></li>\n<li><a href=\"/python/python_xml_processing.htm\" target=\"_top\">Python - XML Processing</a></li>\n<li><a href=\"/python/python_gui_programming.htm\" target=\"_top\">Python - GUI Programming</a></li>\n<li><a href=\"/python/python_further_extensions.htm\" target=\"_top\">Python - Further Extensions</a></li>\n</ul>\n<ul class=\"nav nav-list primary left-menu\">\n<li class=\"heading\">Python  Useful Resources</li>\n<li><a href=\"/python/python_questions_answers.htm\" target=\"_top\">Python - Questions and Answers</a></li>\n<li><a href=\"/python/python_quick_guide.htm\" target=\"_top\">Python - Quick Guide</a></li>\n<li><a href=\"/python/python_tools_utilities.htm\" target=\"_top\">Python - Tools/Utilities</a></li>\n<li><a href=\"/python/python_useful_resources.htm\" target=\"_top\">Python - Useful Resources</a></li>\n<li><a href=\"/python/python_discussion.htm\" target=\"_top\">Python - Discussion</a></li>\n</ul>\n<ul class=\"nav nav-list primary push-bottom left-menu special\">\n<li class=\"sreading\">Selected Reading</li>\n<li><a href=\"/upsc_ias_exams.htm\" target=\"_top\">UPSC IAS Exams Notes</a></li>\n<li><a href=\"/developers_best_practices/index.htm\" target=\"_top\">Developer's Best Practices</a></li>\n<li><a href=\"/questions_and_answers.htm\" target=\"_top\">Questions and Answers</a></li>\n<li><a href=\"/effective_resume_writing.htm\" target=\"_top\">Effective Resume Writing</a></li>\n<li><a href=\"/hr_interview_questions/index.htm\" target=\"_top\">HR Interview Questions</a></li>\n<li><a href=\"/computer_glossary.htm\" target=\"_top\">Computer Glossary</a></li>\n<li><a href=\"/computer_whoiswho.htm\" target=\"_top\">Who is Who</a></li>\n</ul>\n</aside>\n</div>\n<!-- PRINTING STARTS HERE -->\n<div class=\"row\">\n<div class=\"content\">\n<div class=\"col-md-7 middle-col\">\n<h1>Python - Exceptions Handling</h1>\n<hr/>\n<div style=\"padding-bottom:5px;padding-left:10px;text-align: center;\">Advertisements</div>\n<div style=\"text-align: center;\">\n<script type=\"text/javascript\"><!--\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = 468;\ngoogle_ad_height = 60;\ngoogle_ad_format = \"468x60_as\";\ngoogle_ad_type = \"image\";\ngoogle_ad_channel = \"\";\n//--></script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\" type=\"text/javascript\">\n</script>\n</div>\n<hr/>\n<div class=\"pre-btn\">\n<a href=\"/python/python_files_io.htm\"><i class=\"icon icon-arrow-circle-o-left big-font\"></i> Previous Page</a>\n</div>\n<div class=\"nxt-btn\">\n<a href=\"/python/python_classes_objects.htm\">Next Page <i class=\"icon icon-arrow-circle-o-right big-font\"></i>\u00a0</a>\n</div>\n<div class=\"clearer\"></div>\n<hr/>\n<p>Python provides two very important features to handle any unexpected error in your Python programs and to add debugging capabilities in them \u2212</p>\n<ul class=\"list\">\n<li><p><b>Exception Handling</b> \u2212 This would be covered in this tutorial. Here is a list standard Exceptions available in Python: <a href=\"/python/standard_exceptions.htm\">Standard Exceptions</a>.</p></li>\n<li><p><b>Assertions</b> \u2212 This would be covered in <a href=\"/python/assertions_in_python.htm\">Assertions in Python</a> tutorial.</p></li>\n</ul>\n<p>List of Standard Exceptions \u2212</p>\n<table class=\"table table-bordered\">\n<tr>\n<th style=\"text-align:center;\">Sr.No.</th>\n<th style=\"text-align:center;\">Exception Name &amp; Description</th>\n</tr>\n<tr>\n<td class=\"ts\">1</td>\n<td><p><b>Exception</b></p>\n<p>Base class for all exceptions</p></td>\n</tr>\n<tr>\n<td class=\"ts\">2</td>\n<td><p><b>StopIteration</b></p>\n<p>Raised when the next() method of an iterator does not point to any object.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">3</td>\n<td><p><b>SystemExit</b></p>\n<p>Raised by the sys.exit() function.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">4</td>\n<td><p><b>StandardError</b></p>\n<p>Base class for all built-in exceptions except StopIteration and SystemExit.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">5</td>\n<td><p><b>ArithmeticError</b></p>\n<p>Base class for all errors that occur for numeric calculation.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">6</td>\n<td><p><b>OverflowError</b></p>\n<p>Raised when a calculation exceeds maximum limit for a numeric type.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">7</td>\n<td><p><b>FloatingPointError</b></p>\n<p>Raised when a floating point calculation fails.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">8</td>\n<td><p><b>ZeroDivisionError</b></p>\n<p>Raised when division or modulo by zero takes place for all numeric types.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">9</td>\n<td><p><b>AssertionError</b></p>\n<p>Raised in case of failure of the Assert statement.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">10</td>\n<td><p><b>AttributeError</b></p>\n<p>Raised in case of failure of attribute reference or assignment.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">11</td>\n<td><p><b>EOFError</b></p>\n<p>Raised when there is no input from either the raw_input() or input() function and the end of file is reached.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">12</td>\n<td><p><b>ImportError</b></p>\n<p>Raised when an import statement fails.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">13</td>\n<td><p><b>KeyboardInterrupt</b></p>\n<p>Raised when the user interrupts program execution, usually by pressing Ctrl+c.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">14</td>\n<td><p><b>LookupError</b></p>\n<p>Base class for all lookup errors.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">15</td>\n<td><p><b>IndexError</b></p>\n<p>Raised when an index is not found in a sequence.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">16</td>\n<td><p><b>KeyError</b></p>\n<p>Raised when the specified key is not found in the dictionary.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">17</td>\n<td><p><b>NameError</b></p>\n<p>Raised when an identifier is not found in the local or global namespace.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">18</td>\n<td><p><b>UnboundLocalError</b></p>\n<p>Raised when trying to access a local variable in a function or method but no value has been assigned to it.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">19</td>\n<td><p><b>EnvironmentError</b></p>\n<p>Base class for all exceptions that occur outside the Python environment.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">20</td>\n<td><p><b>IOError</b></p>\n<p>Raised when an input/ output operation fails, such as the print statement or the open() function when trying to open a file that does not exist.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">21</td>\n<td><p><b>IOError</b></p>\n<p>Raised for operating system-related errors.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">22</td>\n<td><p><b>SyntaxError</b></p>\n<p>Raised when there is an error in Python syntax.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">23</td>\n<td><p><b>IndentationError</b></p>\n<p>Raised when indentation is not specified properly.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">24</td>\n<td><p><b>SystemError</b></p>\n<p>Raised when the interpreter finds an internal problem, but when this error is encountered the Python interpreter does not exit.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">25</td>\n<td><p><b>SystemExit</b></p>\n<p>Raised when Python interpreter is quit by using the sys.exit() function. If not handled in the code, causes the interpreter to exit.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">26</td>\n<td><p><b>TypeError</b></p>\n<p>Raised when an operation or function is attempted that is invalid for the specified data type.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">27</td>\n<td><p><b>ValueError</b></p>\n<p>Raised when the built-in function for a data type has the valid type of arguments, but the arguments have invalid values specified.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">28</td>\n<td><p><b>RuntimeError</b></p>\n<p>Raised when a generated error does not fall into any category.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">29</td>\n<td><p><b>NotImplementedError</b></p>\n<p>Raised when an abstract method that needs to be implemented in an inherited class is not actually implemented.</p></td>\n</tr>\n</table>\n<h3>Assertions in Python</h3>\n<p>An assertion is a sanity-check that you can turn on or turn off when you are done with your testing of the program.</p>\n<p>The easiest way to think of an assertion is to liken it to a <b>raise-if</b> statement (or to be more accurate, a raise-if-not statement). An expression is tested, and if the result comes up false, an exception is raised.</p>\n<p>Assertions are carried out by the assert statement, the newest keyword to Python, introduced in version 1.5.</p>\n<p>Programmers often place assertions at the start of a function to check for valid input, and after a function call to check for valid output.</p>\n<h3>The <i>assert</i> Statement</h3>\n<p>When it encounters an assert statement, Python evaluates the accompanying expression, which is hopefully true. If the expression is false, Python raises an <i>AssertionError</i> exception.</p>\n<p>The <b>syntax</b> for assert is \u2212</p>\n<pre class=\"result notranslate\">\nassert Expression[, Arguments]\n</pre>\n<p>If the assertion fails, Python uses ArgumentExpression as the argument for the AssertionError. AssertionError exceptions can be caught and handled like any other exception using the try-except statement, but if not handled, they will terminate the program and produce a traceback.</p>\n<h3>Example</h3>\n<p>Here is a function that converts a temperature from degrees Kelvin to degrees Fahrenheit. Since zero degrees Kelvin is as cold as it gets, the function bails out if it sees a negative temperature \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/fBXCk7\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\ndef KelvinToFahrenheit(Temperature):\n   assert (Temperature &gt;= 0),\"Colder than absolute zero!\"\n   return ((Temperature-273)*1.8)+32\nprint KelvinToFahrenheit(273)\nprint int(KelvinToFahrenheit(505.78))\nprint KelvinToFahrenheit(-5)\n</pre>\n<p>When the above code is executed, it produces the following result \u2212</p>\n<pre class=\"result notranslate\">\n32.0\n451\nTraceback (most recent call last):\nFile \"test.py\", line 9, in &lt;module&gt;\nprint KelvinToFahrenheit(-5)\nFile \"test.py\", line 4, in KelvinToFahrenheit\nassert (Temperature &gt;= 0),\"Colder than absolute zero!\"\nAssertionError: Colder than absolute zero!\n</pre>\n<h2>What is Exception?</h2>\n<p>An exception is an event, which occurs during the execution of a program that disrupts the normal flow of the program's instructions. In general, when a Python script encounters a situation that it cannot cope with, it raises an exception. An exception is a Python object that represents an error.</p>\n<p>When a Python script raises an exception, it must either handle the exception immediately otherwise it terminates and quits.</p>\n<h2>Handling an exception</h2>\n<p>If you have some <i>suspicious</i> code that may raise an exception, you can defend your program by placing the suspicious code in a <b>try:</b> block. After the try: block, include an <b>except:</b> statement, followed by a block of code which handles the problem as elegantly as possible.</p>\n<h3>Syntax</h3>\n<p>Here is simple syntax of <i>try....except...else</i> blocks \u2212</p>\n<pre class=\"result notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept <i>ExceptionI</i>:\n   If there is ExceptionI, then execute this block.\nexcept <i>ExceptionII</i>:\n   If there is ExceptionII, then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n</pre>\n<p>Here are few important points about the above-mentioned syntax \u2212</p>\n<ul class=\"list\">\n<li><p>A single try statement can have multiple except statements. This is useful when the try block contains statements that may throw different types of exceptions.</p></li>\n<li><p>You can also provide a generic except clause, which handles any exception.</p></li>\n<li><p>After the except clause(s), you can include an else-clause. The code in the else-block executes if the code in the try: block does not raise an exception.</p></li>\n<li><p>The else-block is a good place for code that does not need the try: block's protection.</p></li>\n</ul>\n<h3>Example</h3>\n<p>This example opens a file, writes content in the, file and comes out gracefully because there is no problem at all \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/wDwtP9\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   fh.write(\"This is my test file for exception handling!!\")\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\nelse:\n   print \"Written content in the file successfully\"\n   fh.close()\n</pre>\n<p>This produces the following result \u2212</p>\n<pre class=\"result notranslate\">\nWritten content in the file successfully\n</pre>\n<h3>Example</h3>\n<p>This example tries to open a file where you do not have write permission, so it raises an exception \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/guvZfU\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"r\")\n   fh.write(\"This is my test file for exception handling!!\")\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\nelse:\n   print \"Written content in the file successfully\"\n</pre>\n<p>This produces the following result \u2212</p>\n<pre class=\"result notranslate\">\nError: can't find file or read data\n</pre>\n<h2>The <i>except</i> Clause with No Exceptions</h2>\n<p>You can also use the except statement with no exceptions defined as follows \u2212</p>\n<pre class=\"result notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept:\n   If there is any exception, then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n</pre>\n<p>This kind of a <b>try-except</b> statement catches all the exceptions that occur. Using this kind of try-except statement is not considered a good programming practice though, because it catches all exceptions but does not make the programmer identify the root cause of the problem that may occur.</p>\n<h2>The <i>except</i> Clause with Multiple Exceptions</h2>\n<p>You can also use the same <i>except</i> statement to handle multiple exceptions as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept(Exception1[, Exception2[,...ExceptionN]]]):\n   If there is any exception from the given exception list, \n   then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n</pre>\n<h2>The try-finally Clause</h2>\n<p>You can use a <b>finally:</b> block along with a <b>try:</b> block. The finally block is a place to put any code that must execute, whether the try-block\nraised an exception or not. The syntax of the try-finally statement is this \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   You do your operations here;\n   ......................\n   Due to any exception, this may be skipped.\nfinally:\n   This would always be executed.\n   ......................\n</pre>\n<p>You cannot use <i>else</i> clause as well along with a finally clause.</p>\n<h3>Example</h3>\n<a class=\"demo\" href=\"http://tpcg.io/Pfq1qs\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   fh.write(\"This is my test file for exception handling!!\")\nfinally:\n   print \"Error: can\\'t find file or read data\"\n</pre>\n<p>If you do not have permission to open the file in writing mode, then this will produce the following result \u2212</p>\n<pre class=\"result notranslate\">\nError: can't find file or read data\n</pre>\n<p>Same example can be written more cleanly as follows \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/5p1Wkr\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   try:\n      fh.write(\"This is my test file for exception handling!!\")\n   finally:\n      print \"Going to close the file\"\n      fh.close()\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\n</pre>\n<p>When an exception is thrown in the <i>try</i> block, the execution immediately passes to the <i>finally</i> block. After all the statements in the <i>finally</i> block are executed, the exception is raised again and is handled in the <i>except</i> statements if present in the next higher layer of the <i>try-except</i> statement.</p>\n<h2>Argument of an Exception</h2>\n<p>An exception can have an <i>argument</i>, which is a value that gives additional information about the problem. The contents  of the argument vary by exception. You capture an exception's argument by supplying a variable in the except clause as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept <i>ExceptionType, Argument</i>:\n   You can print value of Argument here...\n</pre>\n<p>If you write the code to handle a single exception, you can have a variable follow the name of the exception in the except statement. If you are trapping multiple exceptions, you can have a variable follow the tuple of the exception.</p>\n<p>This variable receives the value of the exception mostly containing the cause of the exception. The variable can receive a single value or multiple values in the form of a tuple. This tuple usually contains the error string, the error number, and an error location.</p>\n<h3>Example</h3>\n<p>Following is an example for a single exception \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/Zr1ck8\n\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\n# Define a function here.\ndef temp_convert(var):\n   try:\n      return int(var)\n   except ValueError, Argument:\n      print \"The argument does not contain numbers\\n\", Argument\n\n# Call above function here.\ntemp_convert(\"xyz\");\n</pre>\n<p>This produces the following result \u2212</p>\n<pre class=\"result notranslate\">\nThe argument does not contain numbers\ninvalid literal for int() with base 10: 'xyz'\n</pre>\n<h2>Raising an Exceptions</h2>\n<p>You can raise exceptions in several ways by using the raise statement. The general syntax for the <b>raise</b> statement is as follows.</p>\n<h3>Syntax</h3>\n<pre class=\"result notranslate\">\nraise [Exception [, args [, traceback]]]\n</pre>\n<p>Here, <i>Exception</i> is the type of exception (for example, NameError) and <i>argument</i> is a value for the exception argument. The argument is optional; if not supplied, the exception argument is None.</p>\n<p>The final argument, traceback, is also optional (and rarely used in practice), and if present, is the traceback object used for the exception.</p>\n<h3>Example</h3>\n<p>An exception can be a string, a class or an object. Most of the exceptions that the Python core raises are classes, with an argument that is an instance of the class. Defining new exceptions is quite easy and can be done as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ndef functionName( level ):\n   if level &lt; 1:\n      raise \"Invalid level!\", level\n      # The code below to this would not be executed\n      # if we raise the exception\n</pre>\n<p><b>Note:</b> In order to catch an exception, an \"except\" clause must refer to the same exception thrown either class object or simple string. For example, to capture above exception, we must write the except clause as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   Business Logic here...\nexcept \"Invalid level!\":\n   Exception handling here...\nelse:\n   Rest of the code here...\n</pre>\n<h2>User-Defined Exceptions</h2>\n<p>Python also allows you to create your own exceptions by deriving classes from the standard built-in exceptions.</p>\n<p>Here is an example related to <i>RuntimeError</i>. Here, a class is created that is subclassed from <i>RuntimeError</i>. This is useful when you need to display more specific information when an exception is caught.</p>\n<p>In the try block, the user-defined exception is raised and caught in the except block. The variable e is used to create an instance of the class <i>Networkerror</i>.</p>\n<pre class=\"prettyprint notranslate\">\nclass Networkerror(RuntimeError):\n   def __init__(self, arg):\n      self.args = arg\n</pre>\n<p>So once you defined above class, you can raise the exception as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   raise Networkerror(\"Bad hostname\")\nexcept Networkerror,e:\n   print e.args\n</pre>\n<hr/>\n<div class=\"pre-btn\">\n<a href=\"/python/python_files_io.htm\"><i class=\"icon icon-arrow-circle-o-left big-font\"></i> Previous Page</a>\n</div>\n<div class=\"print-btn center\">\n<a href=\"/cgi-bin/printpage.cgi\" target=\"_blank\"><i class=\"icon icon-print big-font\"></i> Print</a>\n</div>\n<div class=\"nxt-btn\">\n<a href=\"/python/python_classes_objects.htm\">Next Page <i class=\"icon icon-arrow-circle-o-right big-font\"></i>\u00a0</a>\n</div>\n<hr/>\n<!-- PRINTING ENDS HERE -->\n<div class=\"bottomgooglead\">\n<div class=\"bottomadtag\">Advertisements</div>\n<script><!--\nvar width = 580;\nvar height = 400;\nvar format = \"580x400_as\";\nif( window.innerWidth < 468 ){\n   width = 300;\n   height = 250;\n   format = \"300x250_as\";\n}\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = width;\ngoogle_ad_height = height;\ngoogle_ad_format = format;\ngoogle_ad_type = \"image\";\ngoogle_ad_channel =\"\";\n//--></script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n</script>\n</div>\n</div>\n</div>\n<div class=\"row\">\n<div class=\"col-md-3\" id=\"rightbar\">\n<div class=\"simple-ad\">\n<a href=\"javascript:void(0)\" onclick=\"var sTop = window.screen.height/2-(218); var sLeft = window.screen.width/2-(313);window.open('https://www.facebook.com/sharer.php?u=' + 'https://www.tutorialspoint.com/python/python_exceptions.htm','sharer','toolbar=0,status=0,width=626,height=456,top='+sTop+',left='+sLeft);return false;\">\n<img alt=\"img\" src=\"/images/facebookIcon.jpg\">\n</img></a>\n<a href=\"javascript:void(0)\" onclick=\"var sTop = window.screen.height/2-(218); var sLeft = window.screen.width/2-(313);window.open('https://twitter.com/share?url=' + 'https://www.tutorialspoint.com/python/python_exceptions.htm','sharer','toolbar=0,status=0,width=626,height=456,top='+sTop+',left='+sLeft);return false;\">\n<img alt=\"img\" src=\"/images/twitterIcon.jpg\"/>\n</a>\n<a href=\"javascript:void(0)\" onclick=\"var sTop = window.screen.height/2-(218); var sLeft = window.screen.width/2-(313);window.open('https://www.linkedin.com/cws/share?url=' + 'https://www.tutorialspoint.com/python/python_exceptions.htm&amp;title='+ document.title,'sharer','toolbar=0,status=0,width=626,height=456,top='+sTop+',left='+sLeft);return false;\">\n<img alt=\"img\" src=\"/images/linkedinIcon.jpg\"/>\n</a>\n<a href=\"javascript:void(0)\" onclick=\"var sTop = window.screen.height/2-(218); var sLeft = window.screen.width/2-(313);window.open('https://plus.google.com/share?url=https://www.tutorialspoint.com/python/python_exceptions.htm','sharer','toolbar=0,status=0,width=626,height=456,top='+sTop+',left='+sLeft);return false;\">\n<img alt=\"img\" src=\"/images/googlePlusIcon.jpg\"/>\n</a>\n<a href=\"javascript:void(0)\" onclick=\"var sTop = window.screen.height/2-(218); var sLeft = window.screen.width/2-(313);window.open('https://www.stumbleupon.com/submit?url=https://www.tutorialspoint.com/python/python_exceptions.htm&amp;title='+ document.title,'sharer','toolbar=0,status=0,width=626,height=456,top='+sTop+',left='+sLeft);return false;\">\n<img alt=\"img\" src=\"/images/StumbleUponIcon.jpg\"/>\n</a>\n<a href=\"javascript:void(0)\" onclick=\"var sTop = window.screen.height/2-(218); var sLeft = window.screen.width/2-(313);window.open('https://reddit.com/submit?url=https://www.tutorialspoint.com/python/python_exceptions.htm&amp;title='+ document.title,'sharer','toolbar=0,status=0,width=626,height=656,top='+sTop+',left='+sLeft);return false;\">\n<img alt=\"img\" src=\"/images/reddit.jpg\"/>\n</a>\n</div>\n<div class=\"rightgooglead\">\n<script><!--\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = 300;\ngoogle_ad_height = 250;\ngoogle_ad_format = \"300x250_as\";\ngoogle_ad_type = \"image\";\ngoogle_ad_channel =\"\";\n//--></script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n</script>\n</div>\n<div class=\"rightgooglead\">\n<script><!--\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = 300;\ngoogle_ad_height = 600;\ngoogle_ad_format = \"300x600_as\";\ngoogle_ad_type = \"image\";\ngoogle_ad_channel =\"\";\n//--></script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n</script>\n</div>\n<div class=\"rightgooglead\">\n<script><!--\ngoogle_ad_client = \"ca-pub-2537027957187252\";\n/* Right Side Ad */\ngoogle_ad_slot = \"right_side_ad\";\ngoogle_ad_width = 300;\ngoogle_ad_height = 250;\n//-->\n</script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n</script>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n<div class=\"footer-copyright\">\n<div class=\"container\">\n<div class=\"row\">\n<div class=\"col-md-1\">\n<a class=\"logo\" href=\"index.htm\"> <img alt=\"Tutorials Point\" class=\"img-responsive\" src=\"/scripts/img/logo-footer.png\"/> </a>\n</div>\n<div class=\"col-md-4 col-sm-12 col-xs-12\">\n<nav id=\"sub-menu\">\n<ul>\n<li><a href=\"/about/about_privacy.htm\">Privacy Policy</a></li>\n<li><a href=\"/about/about_cookies.htm\">Cookies Policy</a></li>\n<li><a href=\"/about/contact_us.htm\">Contact</a></li>\n</ul>\n</nav>\n</div>\n<div class=\"col-md-3 col-sm-12 col-xs-12\">\n<p>\u00a9 Copyright 2019. All Rights Reserved.</p>\n</div>\n<div class=\"col-md-4 col-sm-12 col-xs-12\">\n<div class=\"news-group\">\n<input autocomplete=\"off\" class=\"form-control-foot search\" id=\"textemail\" name=\"textemail\" onblur=\"if (this.value == '') {this.value = 'Enter email for newsletter...';}\" onfocus=\"if (this.value == 'Enter email for newsletter...') {this.value = '';}\" placeholder=\"Enter email for newsletter\" type=\"text\"/>\n<span class=\"input-group-btn\"> <button class=\"btn btn-default btn-footer\" id=\"btnemail\" onclick=\"javascript:void(0);\" type=\"submit\">go</button> </span>\n<div id=\"newsresponse\"></div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n<div id=\"privacy-banner\">\n<div>\n<p>\n      We use cookies to provide and improve our services. By using our site, you consent to our Cookies Policy.\n      <a href=\"javascript:void(0)\" id=\"banner-accept\">Accept</a>\n<a href=\"/about/about_cookies.htm\" id=\"banner-learn\" target=\"_blank\">Learn more</a>\n</p>\n</div>\n</div>\n<script>\n// Banner Trigger if Not Closed\nif (!localStorage.bannerClosed) {\n  document.getElementById('privacy-banner').style.display = \"inherit\";\n} else {\n  document.getElementById('privacy-banner').style.display = \"none\";\n}\ndocument.getElementById('banner-accept').addEventListener('click', function() {\n  document.getElementById('privacy-banner').style.display = \"none\";\n  localStorage.bannerClosed = 'true';\n});\nif (navigator.userAgent.match(/Opera|OPR\\//)) {\n  document.getElementById('privacy-banner').style.display = \"inherit\";\n}\n</script>\n<!-- Libs -->\n<script src=\"/theme/js/custom-min.js?v=7\"></script>\n<script src=\"https://www.google-analytics.com/urchin.js\">\n</script>\n<script>\n_uacct = \"UA-232293-6\";\nurchinTracker();\n$('.pg-icon').click(function(){\n   $('.wrapLoader').show();\n});\n</script>\n<script src=\"/theme/js/jquery.colorbox-min.js\"></script>\n<script>\n   var tryit = new $.TryIt('/python/try_python.php');\n   tryit.compile();\n</script>\n\n\n", "title": "Python - Exceptions Handling", "content_html": "<div class=\"col-md-7 middle-col\">\n<h1>Python - Exceptions Handling</h1>\n<hr/>\n<div style=\"padding-bottom:5px;padding-left:10px;text-align: center;\">Advertisements</div>\n<div style=\"text-align: center;\">\n<script type=\"text/javascript\"><!--\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = 468;\ngoogle_ad_height = 60;\ngoogle_ad_format = \"468x60_as\";\ngoogle_ad_type = \"image\";\ngoogle_ad_channel = \"\";\n//--></script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\" type=\"text/javascript\">\n</script>\n</div>\n<hr/>\n<div class=\"pre-btn\">\n<a href=\"/python/python_files_io.htm\"><i class=\"icon icon-arrow-circle-o-left big-font\"></i> Previous Page</a>\n</div>\n<div class=\"nxt-btn\">\n<a href=\"/python/python_classes_objects.htm\">Next Page <i class=\"icon icon-arrow-circle-o-right big-font\"></i>\u00a0</a>\n</div>\n<div class=\"clearer\"></div>\n<hr/>\n<p>Python provides two very important features to handle any unexpected error in your Python programs and to add debugging capabilities in them \u2212</p>\n<ul class=\"list\">\n<li><p><b>Exception Handling</b> \u2212 This would be covered in this tutorial. Here is a list standard Exceptions available in Python: <a href=\"/python/standard_exceptions.htm\">Standard Exceptions</a>.</p></li>\n<li><p><b>Assertions</b> \u2212 This would be covered in <a href=\"/python/assertions_in_python.htm\">Assertions in Python</a> tutorial.</p></li>\n</ul>\n<p>List of Standard Exceptions \u2212</p>\n<table class=\"table table-bordered\">\n<tr>\n<th style=\"text-align:center;\">Sr.No.</th>\n<th style=\"text-align:center;\">Exception Name &amp; Description</th>\n</tr>\n<tr>\n<td class=\"ts\">1</td>\n<td><p><b>Exception</b></p>\n<p>Base class for all exceptions</p></td>\n</tr>\n<tr>\n<td class=\"ts\">2</td>\n<td><p><b>StopIteration</b></p>\n<p>Raised when the next() method of an iterator does not point to any object.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">3</td>\n<td><p><b>SystemExit</b></p>\n<p>Raised by the sys.exit() function.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">4</td>\n<td><p><b>StandardError</b></p>\n<p>Base class for all built-in exceptions except StopIteration and SystemExit.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">5</td>\n<td><p><b>ArithmeticError</b></p>\n<p>Base class for all errors that occur for numeric calculation.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">6</td>\n<td><p><b>OverflowError</b></p>\n<p>Raised when a calculation exceeds maximum limit for a numeric type.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">7</td>\n<td><p><b>FloatingPointError</b></p>\n<p>Raised when a floating point calculation fails.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">8</td>\n<td><p><b>ZeroDivisionError</b></p>\n<p>Raised when division or modulo by zero takes place for all numeric types.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">9</td>\n<td><p><b>AssertionError</b></p>\n<p>Raised in case of failure of the Assert statement.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">10</td>\n<td><p><b>AttributeError</b></p>\n<p>Raised in case of failure of attribute reference or assignment.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">11</td>\n<td><p><b>EOFError</b></p>\n<p>Raised when there is no input from either the raw_input() or input() function and the end of file is reached.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">12</td>\n<td><p><b>ImportError</b></p>\n<p>Raised when an import statement fails.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">13</td>\n<td><p><b>KeyboardInterrupt</b></p>\n<p>Raised when the user interrupts program execution, usually by pressing Ctrl+c.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">14</td>\n<td><p><b>LookupError</b></p>\n<p>Base class for all lookup errors.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">15</td>\n<td><p><b>IndexError</b></p>\n<p>Raised when an index is not found in a sequence.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">16</td>\n<td><p><b>KeyError</b></p>\n<p>Raised when the specified key is not found in the dictionary.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">17</td>\n<td><p><b>NameError</b></p>\n<p>Raised when an identifier is not found in the local or global namespace.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">18</td>\n<td><p><b>UnboundLocalError</b></p>\n<p>Raised when trying to access a local variable in a function or method but no value has been assigned to it.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">19</td>\n<td><p><b>EnvironmentError</b></p>\n<p>Base class for all exceptions that occur outside the Python environment.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">20</td>\n<td><p><b>IOError</b></p>\n<p>Raised when an input/ output operation fails, such as the print statement or the open() function when trying to open a file that does not exist.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">21</td>\n<td><p><b>IOError</b></p>\n<p>Raised for operating system-related errors.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">22</td>\n<td><p><b>SyntaxError</b></p>\n<p>Raised when there is an error in Python syntax.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">23</td>\n<td><p><b>IndentationError</b></p>\n<p>Raised when indentation is not specified properly.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">24</td>\n<td><p><b>SystemError</b></p>\n<p>Raised when the interpreter finds an internal problem, but when this error is encountered the Python interpreter does not exit.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">25</td>\n<td><p><b>SystemExit</b></p>\n<p>Raised when Python interpreter is quit by using the sys.exit() function. If not handled in the code, causes the interpreter to exit.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">26</td>\n<td><p><b>TypeError</b></p>\n<p>Raised when an operation or function is attempted that is invalid for the specified data type.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">27</td>\n<td><p><b>ValueError</b></p>\n<p>Raised when the built-in function for a data type has the valid type of arguments, but the arguments have invalid values specified.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">28</td>\n<td><p><b>RuntimeError</b></p>\n<p>Raised when a generated error does not fall into any category.</p></td>\n</tr>\n<tr>\n<td class=\"ts\">29</td>\n<td><p><b>NotImplementedError</b></p>\n<p>Raised when an abstract method that needs to be implemented in an inherited class is not actually implemented.</p></td>\n</tr>\n</table>\n<h3>Assertions in Python</h3>\n<p>An assertion is a sanity-check that you can turn on or turn off when you are done with your testing of the program.</p>\n<p>The easiest way to think of an assertion is to liken it to a <b>raise-if</b> statement (or to be more accurate, a raise-if-not statement). An expression is tested, and if the result comes up false, an exception is raised.</p>\n<p>Assertions are carried out by the assert statement, the newest keyword to Python, introduced in version 1.5.</p>\n<p>Programmers often place assertions at the start of a function to check for valid input, and after a function call to check for valid output.</p>\n<h3>The <i>assert</i> Statement</h3>\n<p>When it encounters an assert statement, Python evaluates the accompanying expression, which is hopefully true. If the expression is false, Python raises an <i>AssertionError</i> exception.</p>\n<p>The <b>syntax</b> for assert is \u2212</p>\n<pre class=\"result notranslate\">\nassert Expression[, Arguments]\n</pre>\n<p>If the assertion fails, Python uses ArgumentExpression as the argument for the AssertionError. AssertionError exceptions can be caught and handled like any other exception using the try-except statement, but if not handled, they will terminate the program and produce a traceback.</p>\n<h3>Example</h3>\n<p>Here is a function that converts a temperature from degrees Kelvin to degrees Fahrenheit. Since zero degrees Kelvin is as cold as it gets, the function bails out if it sees a negative temperature \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/fBXCk7\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\ndef KelvinToFahrenheit(Temperature):\n   assert (Temperature &gt;= 0),\"Colder than absolute zero!\"\n   return ((Temperature-273)*1.8)+32\nprint KelvinToFahrenheit(273)\nprint int(KelvinToFahrenheit(505.78))\nprint KelvinToFahrenheit(-5)\n</pre>\n<p>When the above code is executed, it produces the following result \u2212</p>\n<pre class=\"result notranslate\">\n32.0\n451\nTraceback (most recent call last):\nFile \"test.py\", line 9, in &lt;module&gt;\nprint KelvinToFahrenheit(-5)\nFile \"test.py\", line 4, in KelvinToFahrenheit\nassert (Temperature &gt;= 0),\"Colder than absolute zero!\"\nAssertionError: Colder than absolute zero!\n</pre>\n<h2>What is Exception?</h2>\n<p>An exception is an event, which occurs during the execution of a program that disrupts the normal flow of the program's instructions. In general, when a Python script encounters a situation that it cannot cope with, it raises an exception. An exception is a Python object that represents an error.</p>\n<p>When a Python script raises an exception, it must either handle the exception immediately otherwise it terminates and quits.</p>\n<h2>Handling an exception</h2>\n<p>If you have some <i>suspicious</i> code that may raise an exception, you can defend your program by placing the suspicious code in a <b>try:</b> block. After the try: block, include an <b>except:</b> statement, followed by a block of code which handles the problem as elegantly as possible.</p>\n<h3>Syntax</h3>\n<p>Here is simple syntax of <i>try....except...else</i> blocks \u2212</p>\n<pre class=\"result notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept <i>ExceptionI</i>:\n   If there is ExceptionI, then execute this block.\nexcept <i>ExceptionII</i>:\n   If there is ExceptionII, then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n</pre>\n<p>Here are few important points about the above-mentioned syntax \u2212</p>\n<ul class=\"list\">\n<li><p>A single try statement can have multiple except statements. This is useful when the try block contains statements that may throw different types of exceptions.</p></li>\n<li><p>You can also provide a generic except clause, which handles any exception.</p></li>\n<li><p>After the except clause(s), you can include an else-clause. The code in the else-block executes if the code in the try: block does not raise an exception.</p></li>\n<li><p>The else-block is a good place for code that does not need the try: block's protection.</p></li>\n</ul>\n<h3>Example</h3>\n<p>This example opens a file, writes content in the, file and comes out gracefully because there is no problem at all \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/wDwtP9\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   fh.write(\"This is my test file for exception handling!!\")\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\nelse:\n   print \"Written content in the file successfully\"\n   fh.close()\n</pre>\n<p>This produces the following result \u2212</p>\n<pre class=\"result notranslate\">\nWritten content in the file successfully\n</pre>\n<h3>Example</h3>\n<p>This example tries to open a file where you do not have write permission, so it raises an exception \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/guvZfU\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"r\")\n   fh.write(\"This is my test file for exception handling!!\")\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\nelse:\n   print \"Written content in the file successfully\"\n</pre>\n<p>This produces the following result \u2212</p>\n<pre class=\"result notranslate\">\nError: can't find file or read data\n</pre>\n<h2>The <i>except</i> Clause with No Exceptions</h2>\n<p>You can also use the except statement with no exceptions defined as follows \u2212</p>\n<pre class=\"result notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept:\n   If there is any exception, then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n</pre>\n<p>This kind of a <b>try-except</b> statement catches all the exceptions that occur. Using this kind of try-except statement is not considered a good programming practice though, because it catches all exceptions but does not make the programmer identify the root cause of the problem that may occur.</p>\n<h2>The <i>except</i> Clause with Multiple Exceptions</h2>\n<p>You can also use the same <i>except</i> statement to handle multiple exceptions as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept(Exception1[, Exception2[,...ExceptionN]]]):\n   If there is any exception from the given exception list, \n   then execute this block.\n   ......................\nelse:\n   If there is no exception then execute this block. \n</pre>\n<h2>The try-finally Clause</h2>\n<p>You can use a <b>finally:</b> block along with a <b>try:</b> block. The finally block is a place to put any code that must execute, whether the try-block\nraised an exception or not. The syntax of the try-finally statement is this \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   You do your operations here;\n   ......................\n   Due to any exception, this may be skipped.\nfinally:\n   This would always be executed.\n   ......................\n</pre>\n<p>You cannot use <i>else</i> clause as well along with a finally clause.</p>\n<h3>Example</h3>\n<a class=\"demo\" href=\"http://tpcg.io/Pfq1qs\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   fh.write(\"This is my test file for exception handling!!\")\nfinally:\n   print \"Error: can\\'t find file or read data\"\n</pre>\n<p>If you do not have permission to open the file in writing mode, then this will produce the following result \u2212</p>\n<pre class=\"result notranslate\">\nError: can't find file or read data\n</pre>\n<p>Same example can be written more cleanly as follows \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/5p1Wkr\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\ntry:\n   fh = open(\"testfile\", \"w\")\n   try:\n      fh.write(\"This is my test file for exception handling!!\")\n   finally:\n      print \"Going to close the file\"\n      fh.close()\nexcept IOError:\n   print \"Error: can\\'t find file or read data\"\n</pre>\n<p>When an exception is thrown in the <i>try</i> block, the execution immediately passes to the <i>finally</i> block. After all the statements in the <i>finally</i> block are executed, the exception is raised again and is handled in the <i>except</i> statements if present in the next higher layer of the <i>try-except</i> statement.</p>\n<h2>Argument of an Exception</h2>\n<p>An exception can have an <i>argument</i>, which is a value that gives additional information about the problem. The contents  of the argument vary by exception. You capture an exception's argument by supplying a variable in the except clause as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   You do your operations here;\n   ......................\nexcept <i>ExceptionType, Argument</i>:\n   You can print value of Argument here...\n</pre>\n<p>If you write the code to handle a single exception, you can have a variable follow the name of the exception in the except statement. If you are trapping multiple exceptions, you can have a variable follow the tuple of the exception.</p>\n<p>This variable receives the value of the exception mostly containing the cause of the exception. The variable can receive a single value or multiple values in the form of a tuple. This tuple usually contains the error string, the error number, and an error location.</p>\n<h3>Example</h3>\n<p>Following is an example for a single exception \u2212</p>\n<a class=\"demo\" href=\"http://tpcg.io/Zr1ck8\n\" rel=\"nofollow\" target=\"_blank\"><i class=\"fa-external-link\"></i> Live Demo</a>\n<pre class=\"prettyprint notranslate\">\n#!/usr/bin/python\n\n# Define a function here.\ndef temp_convert(var):\n   try:\n      return int(var)\n   except ValueError, Argument:\n      print \"The argument does not contain numbers\\n\", Argument\n\n# Call above function here.\ntemp_convert(\"xyz\");\n</pre>\n<p>This produces the following result \u2212</p>\n<pre class=\"result notranslate\">\nThe argument does not contain numbers\ninvalid literal for int() with base 10: 'xyz'\n</pre>\n<h2>Raising an Exceptions</h2>\n<p>You can raise exceptions in several ways by using the raise statement. The general syntax for the <b>raise</b> statement is as follows.</p>\n<h3>Syntax</h3>\n<pre class=\"result notranslate\">\nraise [Exception [, args [, traceback]]]\n</pre>\n<p>Here, <i>Exception</i> is the type of exception (for example, NameError) and <i>argument</i> is a value for the exception argument. The argument is optional; if not supplied, the exception argument is None.</p>\n<p>The final argument, traceback, is also optional (and rarely used in practice), and if present, is the traceback object used for the exception.</p>\n<h3>Example</h3>\n<p>An exception can be a string, a class or an object. Most of the exceptions that the Python core raises are classes, with an argument that is an instance of the class. Defining new exceptions is quite easy and can be done as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ndef functionName( level ):\n   if level &lt; 1:\n      raise \"Invalid level!\", level\n      # The code below to this would not be executed\n      # if we raise the exception\n</pre>\n<p><b>Note:</b> In order to catch an exception, an \"except\" clause must refer to the same exception thrown either class object or simple string. For example, to capture above exception, we must write the except clause as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   Business Logic here...\nexcept \"Invalid level!\":\n   Exception handling here...\nelse:\n   Rest of the code here...\n</pre>\n<h2>User-Defined Exceptions</h2>\n<p>Python also allows you to create your own exceptions by deriving classes from the standard built-in exceptions.</p>\n<p>Here is an example related to <i>RuntimeError</i>. Here, a class is created that is subclassed from <i>RuntimeError</i>. This is useful when you need to display more specific information when an exception is caught.</p>\n<p>In the try block, the user-defined exception is raised and caught in the except block. The variable e is used to create an instance of the class <i>Networkerror</i>.</p>\n<pre class=\"prettyprint notranslate\">\nclass Networkerror(RuntimeError):\n   def __init__(self, arg):\n      self.args = arg\n</pre>\n<p>So once you defined above class, you can raise the exception as follows \u2212</p>\n<pre class=\"prettyprint notranslate\">\ntry:\n   raise Networkerror(\"Bad hostname\")\nexcept Networkerror,e:\n   print e.args\n</pre>\n<hr/>\n<div class=\"pre-btn\">\n<a href=\"/python/python_files_io.htm\"><i class=\"icon icon-arrow-circle-o-left big-font\"></i> Previous Page</a>\n</div>\n<div class=\"print-btn center\">\n<a href=\"/cgi-bin/printpage.cgi\" target=\"_blank\"><i class=\"icon icon-print big-font\"></i> Print</a>\n</div>\n<div class=\"nxt-btn\">\n<a href=\"/python/python_classes_objects.htm\">Next Page <i class=\"icon icon-arrow-circle-o-right big-font\"></i>\u00a0</a>\n</div>\n<hr/>\n<!-- PRINTING ENDS HERE -->\n<div class=\"bottomgooglead\">\n<div class=\"bottomadtag\">Advertisements</div>\n<script><!--\nvar width = 580;\nvar height = 400;\nvar format = \"580x400_as\";\nif( window.innerWidth < 468 ){\n   width = 300;\n   height = 250;\n   format = \"300x250_as\";\n}\ngoogle_ad_client = \"pub-7133395778201029\";\ngoogle_ad_width = width;\ngoogle_ad_height = height;\ngoogle_ad_format = format;\ngoogle_ad_type = \"image\";\ngoogle_ad_channel =\"\";\n//--></script>\n<script src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n</script>\n</div>\n</div>"}